name: NPM Publish

# Conventional Commits:
# feat: Nueva característica                      → incrementa versión menor     (1.x.0)
# fix: Arreglo de bug                             → incrementa versión de parche (1.0.x)
# feat: Nueva característica BREAKING CHANGE: ... → incrementa versión mayor     (x.0.0)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm test
      
      - name: Run Lint
        run: npm run lint

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:  
      contents: write  # Para crear tags
      pull-requests: write # Para crear pull requests
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bump Version and Create Tag
        id: bump-version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
      
      - name: Update Version in package.json
        run: |
          npm version ${{ steps.bump-version.outputs.new_version }} --no-git-tag-version
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to ${{ steps.bump-version.outputs.new_version }} [skip ci]"
          git push
      
      - name: Build Project
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

